#!/bin/bash


rm -rf documentation
mkdir documentation

for i in custom*.xml; do 
   DOCUFILE="documentation/${i%%.xml}.html"
   DOCUFILE="$(echo $DOCUFILE|tr ' ' '_')"
   xalan -in "$i" -out $DOCUFILE -xsl transform.xsl; 
done

